/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.CCart;
import Controller.CMessageManagement;
import Controller.COrder;
import com.sun.corba.se.impl.protocol.giopmsgheaders.ReplyMessage;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Ockersz
 */
public class VCart extends javax.swing.JInternalFrame {
    /**
     * Creates new form VCart
     */
    public VCart() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null); //internal frame wont be able to move
        
        txt_bill.setEditable(false); // text area cannot be edited
        refreshCart();
        cal();
    }
    
    public void refreshCart()
    {
        ResultSet rs = (ResultSet) CCart.loadCart();
        DefaultTableModel dtm = new DefaultTableModel(); 
        
        tbl_cart.getTableHeader().setReorderingAllowed(false);
        dtm.addColumn("Id");
        dtm.addColumn("Name");
        dtm.addColumn("Quantity");
        dtm.addColumn("Sub Total");
        
        
        try{
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(),"Cart is empty, please add products first");
            }
            else{
            do
            {
                String[] values = new String[4];
                values[0] = Integer.toString(rs.getInt(1));
                values[1] = rs.getString(2);
                values[2] = Integer.toString(rs.getInt(3));
                values[3] = Integer.toString(rs.getInt(4));
                
                dtm.addRow(values);
            }
            while(rs.next());
            tbl_cart.setModel(dtm);
            tbl_cart.getColumnModel().getColumn(1).setPreferredWidth(150);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(),e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_del = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_bill = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cart = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_balance = new javax.swing.JLabel();
        txt_tot = new javax.swing.JLabel();
        txt_cashpay = new javax.swing.JTextField();
        btn_pay = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        btn_clearcart = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(46, 51, 73));
        jPanel1.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(158, 161, 176));
        jLabel1.setText("CART");

        btn_del.setBackground(new java.awt.Color(204, 0, 0));
        btn_del.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_del.setText("Delete Selected Item");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        txt_bill.setColumns(20);
        txt_bill.setRows(5);
        jScrollPane2.setViewportView(txt_bill);

        tbl_cart.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tbl_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Iteam", "Qty", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cart.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbl_cart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl_cart.setDoubleBuffered(true);
        tbl_cart.setFocusable(false);
        tbl_cart.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_cart.setMinimumSize(new java.awt.Dimension(150, 0));
        tbl_cart.setRowHeight(25);
        tbl_cart.getTableHeader().setResizingAllowed(false);
        tbl_cart.getTableHeader().setReorderingAllowed(false);
        TableColumnModel col = tbl_cart.getColumnModel();
        TableColumn tc = col.getColumn(1);
        tc.setPreferredWidth(150);
        tbl_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cart);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setText("Total :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel3.setText("Cash :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel4.setText("Balance :");

        txt_balance.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txt_balance.setText("00");

        txt_tot.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        txt_tot.setText("00");

        txt_cashpay.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N

        btn_pay.setBackground(new java.awt.Color(41, 163, 41));
        btn_pay.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn_pay.setText("Pay");
        btn_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_payActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(0, 128, 255));
        btn_print.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tot, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cashpay, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cashpay)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_balance)))
                    .addComponent(btn_pay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btn_print, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_clearcart.setBackground(new java.awt.Color(204, 0, 0));
        btn_clearcart.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btn_clearcart.setText("Clear Cart");
        btn_clearcart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearcartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_del)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_clearcart, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearcart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_cartMouseClicked

    private void btn_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_payActionPerformed
        // pay btn
        if(txt_cashpay.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "Input cash amount to pay");
        }
               
        else if(!txt_cashpay.getText().matches("\\d+"))
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "Cash amount cannot contain letters");
        }
                
        else{
            if(tbl_cart.getModel().getRowCount()==0)
            {
                JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "Your cart does not have any products to make payment","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            
            else{
            int tot = Integer.parseInt(txt_tot.getText());
            int paid = Integer.parseInt(txt_cashpay.getText());
            int balance =0;
            
            if(tot<paid)
            {
             balance = paid - tot ;
            
           // DecimalFormat df = new DecimalFormat("00.00") ;
        
            txt_balance.setText(String.valueOf(balance));
            
            COrder.makeOrder(Integer.parseInt(txt_tot.getText()), VLogin.emp_id);
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "Order made Successfully","Info",JOptionPane.INFORMATION_MESSAGE);
            
            showReceipt();
            CCart.emptyCart();
            DefaultTableModel dt = (DefaultTableModel) tbl_cart.getModel();
            dt.setRowCount(0);
            
            }
            else
            {
                JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "The amount given is not sufficient");
            }
           
            }
        }
    }//GEN-LAST:event_btn_payActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // bill print
        if(txt_bill.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "Reciept is not available to print","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        try {
  
            txt_bill.print(); //print

        } catch (PrinterException e) {

            System.out.println(e);

        }
        }

    }//GEN-LAST:event_btn_printActionPerformed
    public void showReceipt()
    {
        
            txt_bill.setText("                                                      NIBM \n");
            txt_bill.setText(txt_bill.getText() + "                                             Vijayarama Rd, \n");
            txt_bill.setText(txt_bill.getText() + "                                          Colombo 07, Sri lanka, \n");
            txt_bill.setText(txt_bill.getText() + "                                           +9411 123456789, \n");
            txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------------------------------\n");
            txt_bill.setText(txt_bill.getText() + "  Item \t\t Qty \tPrice" +"\n");
            txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------------------------------\n");

            DefaultTableModel df = (DefaultTableModel) tbl_cart.getModel();

            // get table Product details

            for (int i = 0; i < tbl_cart.getRowCount(); i++) {

                String Name = df.getValueAt(i, 1).toString();
                String Qty = df.getValueAt(i, 2).toString();
                String Price = df.getValueAt(i, 3).toString();

                txt_bill.setText(txt_bill.getText() +"  "+ Name+"\t"+"\t"+Qty +"\t"+Price + "\n");
            }

            txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------------------------------\n");
            txt_bill.setText(txt_bill.getText() + "Total\t: " + txt_tot.getText() +"\n");
            txt_bill.setText(txt_bill.getText() + "Cash\t: " + txt_cashpay.getText() +"\n");
            txt_bill.setText(txt_bill.getText() + "Balance\t: " + txt_balance.getText() +"\n");
            txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------------------------------\n");
            txt_bill.setText(txt_bill.getText() + "                              Thanks You Come Again...!"+"\n");
            txt_bill.setText(txt_bill.getText() + "                                        Receip ID : "+COrder.getOid()+" "+"\n");
            txt_bill.setText(txt_bill.getText() + "---------------------------------------------------------------------------------------------\n");
            txt_bill.setText(txt_bill.getText() + "                              Software by CODSE212F-003"+"\n");

    }
    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // delete some item

        DefaultTableModel dt = (DefaultTableModel) tbl_cart.getModel();

        
        if(tbl_cart.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(),"Please select an item to delete","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        String r = dt.getValueAt(tbl_cart.getSelectedRow(), 0).toString();
        CCart.deleteItem(Integer.parseInt(r));
        
        int rw = tbl_cart.getSelectedRow();
        dt.removeRow(rw); 
        
        refreshCart();
        cal(); // after iteam delete calculate total
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_clearcartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearcartActionPerformed
        // TODO add your handling code here:
        int reply = JOptionPane.showConfirmDialog(CMessageManagement.getVisibleContent(),"Do you want to clear the cart?","Clear Cart",JOptionPane.YES_NO_OPTION);
        if(reply == JOptionPane.YES_OPTION)
        {
            DefaultTableModel dt = (DefaultTableModel) tbl_cart.getModel();
            
            dt.setRowCount(0);
            CCart.emptyCart();
            refreshCart();
            cal();
        }
        else
        {
            
        }
    }//GEN-LAST:event_btn_clearcartActionPerformed

     public void cal(){
    //cal total table values
   
        int numOfRow = tbl_cart.getRowCount() ;
        int tot = 0 ;
   
        for (int i = 0; i < numOfRow; i++) {
           
           double value = Double.valueOf(tbl_cart.getValueAt(i, 3).toString());
          
           tot += value ;
           
        }
       
       //DecimalFormat df = new DecimalFormat("00.00") ;
       txt_tot.setText(Integer.toString(tot));
    
   
   
   } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clearcart;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_pay;
    private javax.swing.JButton btn_print;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_cart;
    private javax.swing.JLabel txt_balance;
    private javax.swing.JTextArea txt_bill;
    private javax.swing.JTextField txt_cashpay;
    private javax.swing.JLabel txt_tot;
    // End of variables declaration//GEN-END:variables
}
