/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author Ockersz
 */
public class VDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VDashboard
     */
    Color panedefault;
    Color paneClick;
    public VDashboard() {
        initComponents();
        
        panedefault = new Color(24, 30, 54);
        paneClick = new Color(0, 126, 249);
        panel_home.setBackground(panedefault);
        panel_products.setBackground(panedefault);
        panel_orders.setBackground(panedefault);
        panel_reports.setBackground(panedefault);
        panel_cart.setBackground(panedefault);
        jpanel_cart.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      nav_panel = new javax.swing.JPanel();
      jPanel1 = new javax.swing.JPanel();
      panel_home = new javax.swing.JPanel();
      lbl_home = new javax.swing.JLabel();
      jPanel5 = new javax.swing.JPanel();
      panel_products = new javax.swing.JPanel();
      lbl_prodcts = new javax.swing.JLabel();
      jPanel3 = new javax.swing.JPanel();
      panel_orders = new javax.swing.JPanel();
      lbl_orders = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      btn_logout = new javax.swing.JButton();
      jPanel4 = new javax.swing.JPanel();
      panel_reports = new javax.swing.JPanel();
      lbl_orders1 = new javax.swing.JLabel();
      jpanel_cart = new javax.swing.JPanel();
      panel_cart = new javax.swing.JPanel();
      lbl_orders2 = new javax.swing.JLabel();
      jDesktopPane1 = new javax.swing.JDesktopPane();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("DASHBOARD");
      setBackground(new java.awt.Color(0, 0, 51));
      setPreferredSize(new java.awt.Dimension(1147, 920));
      setSize(new java.awt.Dimension(1147, 920));

      nav_panel.setBackground(new java.awt.Color(24, 30, 54));

      jPanel1.setBackground(new java.awt.Color(24, 30, 54));
      jPanel1.setForeground(new java.awt.Color(0, 126, 249));
      jPanel1.setToolTipText("");
      jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jPanel1MouseClicked(evt);
         }
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jPanel1MousePressed(evt);
         }
      });

      javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
      panel_home.setLayout(panel_homeLayout);
      panel_homeLayout.setHorizontalGroup(
         panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 15, Short.MAX_VALUE)
      );
      panel_homeLayout.setVerticalGroup(
         panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 50, Short.MAX_VALUE)
      );

      lbl_home.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      lbl_home.setForeground(new java.awt.Color(0, 126, 249));
      lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesAndIcons/home.png"))); // NOI18N
      lbl_home.setText("HOME");
      lbl_home.setAlignmentY(0.0F);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbl_home)
            .addGap(0, 186, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_home)
            .addContainerGap())
      );

      jPanel5.setBackground(new java.awt.Color(24, 30, 54));
      jPanel5.setForeground(new java.awt.Color(0, 126, 249));
      jPanel5.setToolTipText("");
      jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jPanel5MouseClicked(evt);
         }
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jPanel5MousePressed(evt);
         }
      });

      javax.swing.GroupLayout panel_productsLayout = new javax.swing.GroupLayout(panel_products);
      panel_products.setLayout(panel_productsLayout);
      panel_productsLayout.setHorizontalGroup(
         panel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 15, Short.MAX_VALUE)
      );
      panel_productsLayout.setVerticalGroup(
         panel_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 50, Short.MAX_VALUE)
      );

      lbl_prodcts.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      lbl_prodcts.setForeground(new java.awt.Color(0, 126, 249));
      lbl_prodcts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesAndIcons/diagram.png"))); // NOI18N
      lbl_prodcts.setText("PRODUCTS");
      lbl_prodcts.setAlignmentY(0.0F);

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(panel_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbl_prodcts)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(panel_products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_prodcts)
            .addContainerGap())
      );

      jPanel3.setBackground(new java.awt.Color(24, 30, 54));
      jPanel3.setForeground(new java.awt.Color(0, 126, 249));
      jPanel3.setToolTipText("");
      jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jPanel3MouseClicked(evt);
         }
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jPanel3MousePressed(evt);
         }
      });

      javax.swing.GroupLayout panel_ordersLayout = new javax.swing.GroupLayout(panel_orders);
      panel_orders.setLayout(panel_ordersLayout);
      panel_ordersLayout.setHorizontalGroup(
         panel_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 15, Short.MAX_VALUE)
      );
      panel_ordersLayout.setVerticalGroup(
         panel_ordersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 50, Short.MAX_VALUE)
      );

      lbl_orders.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      lbl_orders.setForeground(new java.awt.Color(0, 126, 249));
      lbl_orders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesAndIcons/Order.png"))); // NOI18N
      lbl_orders.setText("ORDERS");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(panel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbl_orders)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(panel_orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_orders)
            .addContainerGap())
      );

      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesAndIcons/alpha logo dashboard 31.png"))); // NOI18N

      btn_logout.setBackground(new java.awt.Color(46, 51, 73));
      btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      btn_logout.setForeground(new java.awt.Color(0, 126, 249));
      btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesAndIcons/Webp.net-resizeimage.png"))); // NOI18N
      btn_logout.setText("LOG OUT");
      btn_logout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_logoutActionPerformed(evt);
         }
      });

      jPanel4.setBackground(new java.awt.Color(24, 30, 54));
      jPanel4.setForeground(new java.awt.Color(0, 126, 249));
      jPanel4.setToolTipText("");
      jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jPanel4MouseClicked(evt);
         }
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jPanel4MousePressed(evt);
         }
      });

      javax.swing.GroupLayout panel_reportsLayout = new javax.swing.GroupLayout(panel_reports);
      panel_reports.setLayout(panel_reportsLayout);
      panel_reportsLayout.setHorizontalGroup(
         panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 15, Short.MAX_VALUE)
      );
      panel_reportsLayout.setVerticalGroup(
         panel_reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 50, Short.MAX_VALUE)
      );

      lbl_orders1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      lbl_orders1.setForeground(new java.awt.Color(0, 126, 249));
      lbl_orders1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesAndIcons/diagram.png"))); // NOI18N
      lbl_orders1.setText("REPORTS");

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(panel_reports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbl_orders1)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(panel_reports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_orders1))
      );

      jpanel_cart.setBackground(new java.awt.Color(24, 30, 54));
      jpanel_cart.setForeground(new java.awt.Color(0, 126, 249));
      jpanel_cart.setToolTipText("");
      jpanel_cart.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jpanel_cartMouseClicked(evt);
         }
         public void mousePressed(java.awt.event.MouseEvent evt) {
            jpanel_cartMousePressed(evt);
         }
      });

      javax.swing.GroupLayout panel_cartLayout = new javax.swing.GroupLayout(panel_cart);
      panel_cart.setLayout(panel_cartLayout);
      panel_cartLayout.setHorizontalGroup(
         panel_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 15, Short.MAX_VALUE)
      );
      panel_cartLayout.setVerticalGroup(
         panel_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 50, Short.MAX_VALUE)
      );

      lbl_orders2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
      lbl_orders2.setForeground(new java.awt.Color(0, 126, 249));
      lbl_orders2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesAndIcons/Order1.png"))); // NOI18N
      lbl_orders2.setText("CART");

      javax.swing.GroupLayout jpanel_cartLayout = new javax.swing.GroupLayout(jpanel_cart);
      jpanel_cart.setLayout(jpanel_cartLayout);
      jpanel_cartLayout.setHorizontalGroup(
         jpanel_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jpanel_cartLayout.createSequentialGroup()
            .addComponent(panel_cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(lbl_orders2)
            .addGap(0, 0, Short.MAX_VALUE))
      );
      jpanel_cartLayout.setVerticalGroup(
         jpanel_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(panel_cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
         .addGroup(jpanel_cartLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lbl_orders2))
      );

      javax.swing.GroupLayout nav_panelLayout = new javax.swing.GroupLayout(nav_panel);
      nav_panel.setLayout(nav_panelLayout);
      nav_panelLayout.setHorizontalGroup(
         nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(nav_panelLayout.createSequentialGroup()
            .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(nav_panelLayout.createSequentialGroup()
                  .addGroup(nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(nav_panelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                     .addGroup(nav_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_logout)))
                  .addGap(0, 19, Short.MAX_VALUE))
               .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jpanel_cart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      nav_panelLayout.setVerticalGroup(
         nav_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(nav_panelLayout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(jLabel1)
            .addGap(28, 28, 28)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
            .addComponent(jpanel_cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(103, 103, 103)
            .addComponent(btn_logout)
            .addContainerGap())
      );

      jDesktopPane1.setBackground(new java.awt.Color(46, 51, 73));

      javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
      jDesktopPane1.setLayout(jDesktopPane1Layout);
      jDesktopPane1Layout.setHorizontalGroup(
         jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 946, Short.MAX_VALUE)
      );
      jDesktopPane1Layout.setVerticalGroup(
         jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(nav_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jDesktopPane1))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(nav_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jDesktopPane1)
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        panel_home.setBackground(paneClick);
        panel_products.setBackground(panedefault);
        panel_orders.setBackground(panedefault);
        panel_reports.setBackground(panedefault);
        panel_cart.setBackground(panedefault);
        jpanel_cart.setVisible(true);
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        panel_home.setBackground(panedefault);
        panel_products.setBackground(paneClick);
        panel_orders.setBackground(panedefault);
        panel_reports.setBackground(panedefault);
        panel_cart.setBackground(panedefault);
        jpanel_cart.setVisible(false);
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        panel_home.setBackground(panedefault);
        panel_products.setBackground(panedefault);
        panel_orders.setBackground(paneClick);
        panel_reports.setBackground(panedefault);
        panel_cart.setBackground(panedefault);
        jpanel_cart.setVisible(false);
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jDesktopPane1.removeAll();
        VHome home = new VHome();
        jDesktopPane1.add(home).setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        jDesktopPane1.removeAll();
        VProduct products = new VProduct();
        jDesktopPane1.add(products).setVisible(true);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        jDesktopPane1.removeAll();
        VOrders orders = new VOrders();
        jDesktopPane1.add(orders).setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        jDesktopPane1.removeAll();
        VReports reports = new VReports();
        jDesktopPane1.add(reports).setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
       panel_home.setBackground(panedefault);
        panel_products.setBackground(panedefault);
        panel_orders.setBackground(panedefault);
        panel_reports.setBackground(paneClick);
        panel_cart.setBackground(panedefault);
        jpanel_cart.setVisible(false);
    }//GEN-LAST:event_jPanel4MousePressed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        VLogin obj = new VLogin();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jpanel_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanel_cartMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        VCart cart = new VCart();
        jDesktopPane1.add(cart).setVisible(true);
    }//GEN-LAST:event_jpanel_cartMouseClicked

    private void jpanel_cartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanel_cartMousePressed
        // TODO add your handling code here:
        panel_home.setBackground(panedefault);
        panel_products.setBackground(panedefault);
        panel_orders.setBackground(panedefault);
        panel_reports.setBackground(panedefault);
        panel_cart.setBackground(paneClick);
    }//GEN-LAST:event_jpanel_cartMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDashboard().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btn_logout;
   private javax.swing.JDesktopPane jDesktopPane1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JPanel jpanel_cart;
   private javax.swing.JLabel lbl_home;
   private javax.swing.JLabel lbl_orders;
   private javax.swing.JLabel lbl_orders1;
   private javax.swing.JLabel lbl_orders2;
   private javax.swing.JLabel lbl_prodcts;
   private javax.swing.JPanel nav_panel;
   private javax.swing.JPanel panel_cart;
   private javax.swing.JPanel panel_home;
   private javax.swing.JPanel panel_orders;
   private javax.swing.JPanel panel_products;
   private javax.swing.JPanel panel_reports;
   // End of variables declaration//GEN-END:variables
}
