/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.CMessageManagement;
import Controller.COrder;
import Controller.CProduct;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ockersz
 */
public class VOrders extends javax.swing.JInternalFrame {

    /**
     * Creates new form VOrders
     */
    public VOrders() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_adderror = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_orderid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_orders = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_products_by_order = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(46, 51, 73));

        txt_adderror.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_adderror.setForeground(new java.awt.Color(204, 0, 0));
        txt_adderror.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 126, 249));
        jLabel3.setText("Order ID");

        tbl_orders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Date", "Price", "Employee ID"
            }
        ));
        tbl_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ordersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_orders);
        if (tbl_orders.getColumnModel().getColumnCount() > 0) {
            tbl_orders.getColumnModel().getColumn(0).setResizable(false);
            tbl_orders.getColumnModel().getColumn(1).setResizable(false);
            tbl_orders.getColumnModel().getColumn(2).setResizable(false);
            tbl_orders.getColumnModel().getColumn(3).setResizable(false);
        }

        btn_refresh.setBackground(new java.awt.Color(46, 51, 73));
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(0, 126, 249));
        btn_refresh.setText("Refresh");
        btn_refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(46, 51, 73));
        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_search.setForeground(new java.awt.Color(0, 126, 249));
        btn_search.setText("SEARCH");
        btn_search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(158, 161, 176));
        jLabel2.setText("ORDERS");

        tbl_products_by_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(tbl_products_by_order);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_orderid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 286, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addComponent(txt_adderror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_orderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_adderror, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        refresh();
      
    }//GEN-LAST:event_btn_refreshActionPerformed
    
    public void refresh()
    {
          tbl_orders.getTableHeader().setReorderingAllowed(false);
        ResultSet rs = COrder.getOrders();

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Order ID");
        dtm.addColumn("Order Date");
        dtm.addColumn("Price");
        dtm.addColumn("Emp ID");
        try{
            while(rs.next()){
                String[] values = new String[8];
                values[0] = Integer.toString(rs.getInt(1));
                values[1] = rs.getDate(2).toString();
                values[2] = Integer.toString(rs.getInt(3));
                values[3] = Integer.toString(rs.getInt(4));
                
                dtm.addRow(values);
            }
            tbl_orders.setModel(dtm);

        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }
    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        if(txt_orderid.getText().isEmpty())
        {
            txt_adderror.setText("*Order Id cannot be blank ");
        }
        else if (!txt_orderid.getText().matches("\\d+"))
        {
            txt_adderror.setText("*Order Id can only contain letters");
        }
        else
        {
            ResultSet rs = COrder.getOrderById(Integer.parseInt(txt_orderid.getText()));
            DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Order ID");
        dtm.addColumn("Order Date");
        dtm.addColumn("Price");
        dtm.addColumn("Emp ID");
        try{
            while(rs.next()){
                String[] values = new String[8];
                values[0] = Integer.toString(rs.getInt(1));
                values[1] = rs.getDate(2).toString();
                values[2] = Integer.toString(rs.getInt(3));
                values[3] = Integer.toString(rs.getInt(4));
                
                dtm.addRow(values);
            }
            tbl_orders.setModel(dtm);

        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void tbl_ordersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ordersMouseClicked
        // TODO add your handling code here:
         int selectedRow = tbl_orders.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel)tbl_orders.getModel();
        int orderid = Integer.parseInt(dtm.getValueAt(selectedRow, 0).toString());
        
        
        DefaultTableModel dtm2 = new DefaultTableModel();
        dtm2.addColumn("Product Name");
        dtm2.addColumn("Quantity");
        
        ResultSet rs = CProduct.getProductByOrderId(orderid);
        try{
            while(rs.next())
            {
                String[] values = new String[2];
                values[0] = rs.getString(1);
                values[1] = Integer.toString(rs.getInt(2));
                dtm2.addRow(values);
            }
            tbl_products_by_order.setModel(dtm2);
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), e.getMessage());
        }
        
    }//GEN-LAST:event_tbl_ordersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_orders;
    private javax.swing.JTable tbl_products_by_order;
    private javax.swing.JLabel txt_adderror;
    private javax.swing.JTextField txt_orderid;
    // End of variables declaration//GEN-END:variables
}
