/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.CMessageManagement;
import Controller.CProduct;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ockersz
 */
public class VProduct extends javax.swing.JInternalFrame {

    /**
     * Creates new form VProduct
     */
    public VProduct() {
        initComponents();
        refresh();
        refreshUpdateTable();
        refreshDeleteTable();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dtp_manufacture = new com.toedter.calendar.JDateChooser();
        dtp_expire = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_upload = new javax.swing.JButton();
        pb_img = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_products = new javax.swing.JTable();
        btn_refresh = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        txt_adderror = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_updateid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_updatename = new javax.swing.JTextField();
        txt_updatebrand = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_updatequantity = new javax.swing.JTextField();
        txt_updateprice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dtp_updatemanufacture = new com.toedter.calendar.JDateChooser();
        dtp_updateexpire = new com.toedter.calendar.JDateChooser();
        pb_updateimg = new javax.swing.JLabel();
        btn_updateupload = new javax.swing.JButton();
        txt_updateerror = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_showupdate = new javax.swing.JTable();
        btn_refreshupdate = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_loadproduct = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txt_deleteid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_showdelete = new javax.swing.JTable();
        btn_refreshdelete = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txt_deleteerror = new javax.swing.JLabel();

        setBackground(new java.awt.Color(46, 51, 73));

        jPanel1.setBackground(new java.awt.Color(46, 51, 73));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(158, 161, 176));
        jLabel2.setText("PRODUCTS");

        jTabbedPane5.setBackground(new java.awt.Color(46, 51, 73));
        jTabbedPane5.setForeground(new java.awt.Color(0, 126, 249));
        jTabbedPane5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(46, 51, 73));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 126, 249));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 126, 249));
        jLabel4.setText("Quantity");

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 126, 249));
        jLabel8.setText("Manufacture date");

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 126, 249));
        jLabel7.setText("Expiry date");

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 126, 249));
        jLabel6.setText("Price");

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 126, 249));
        jLabel5.setText("Brand");

        btn_upload.setBackground(new java.awt.Color(46, 51, 73));
        btn_upload.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_upload.setForeground(new java.awt.Color(0, 126, 249));
        btn_upload.setText("Upload Image");
        btn_upload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        tbl_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Brand", "Quantity", "Manufacture", "Expire", "Price", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_products.getTableHeader().setReorderingAllowed(false);
        tbl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_products);

        btn_refresh.setBackground(new java.awt.Color(46, 51, 73));
        btn_refresh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_refresh.setForeground(new java.awt.Color(0, 126, 249));
        btn_refresh.setText("Refresh");
        btn_refresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(46, 51, 73));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(0, 126, 249));
        btn_add.setText("ADD");
        btn_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        txt_adderror.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_adderror.setForeground(new java.awt.Color(204, 0, 0));
        txt_adderror.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_adderror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(220, 220, 220)
                                .addComponent(pb_img, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_brand, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addGap(99, 99, 99)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(202, 202, 202))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addGap(64, 64, 64)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dtp_manufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtp_expire, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_name)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(476, 476, 476))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(dtp_manufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtp_expire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pb_img, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adderror, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );

        jTabbedPane5.addTab("ADD", jPanel2);

        jPanel3.setBackground(new java.awt.Color(46, 51, 73));

        jLabel16.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 126, 249));
        jLabel16.setText("Product ID");

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 126, 249));
        jLabel10.setText("Brand");

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 126, 249));
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 126, 249));
        jLabel12.setText("Price");

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 126, 249));
        jLabel13.setText("Quantity");

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 126, 249));
        jLabel14.setText("Expiry date");

        jLabel15.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 126, 249));
        jLabel15.setText("Manufacture date");

        btn_updateupload.setBackground(new java.awt.Color(46, 51, 73));
        btn_updateupload.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_updateupload.setForeground(new java.awt.Color(0, 126, 249));
        btn_updateupload.setText("Upload Image");
        btn_updateupload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_updateupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateuploadActionPerformed(evt);
            }
        });

        txt_updateerror.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_updateerror.setForeground(new java.awt.Color(204, 0, 0));
        txt_updateerror.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tbl_showupdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Brand", "Quantity", "Manufacture", "Expire", "Price", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_showupdate.getTableHeader().setReorderingAllowed(false);
        tbl_showupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_showupdateMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_showupdate);

        btn_refreshupdate.setBackground(new java.awt.Color(46, 51, 73));
        btn_refreshupdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_refreshupdate.setForeground(new java.awt.Color(0, 126, 249));
        btn_refreshupdate.setText("Refresh");
        btn_refreshupdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_refreshupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshupdateActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(46, 51, 73));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(0, 126, 249));
        btn_update.setText("UPDATE");
        btn_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_loadproduct.setBackground(new java.awt.Color(46, 51, 73));
        btn_loadproduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_loadproduct.setForeground(new java.awt.Color(0, 126, 249));
        btn_loadproduct.setText("Load");
        btn_loadproduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_loadproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadproductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txt_updateid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_loadproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_updatequantity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(52, 52, 52)
                                        .addComponent(txt_updateprice, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_updateerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15))
                                    .addComponent(btn_updateupload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_updatename))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(11, 11, 11)
                                                .addComponent(txt_updatebrand, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel16)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(286, 286, 286)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(pb_updateimg, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtp_updateexpire, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtp_updatemanufacture, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_refreshupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_updateid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(btn_loadproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txt_updatename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(txt_updatequantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(dtp_updatemanufacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txt_updatebrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txt_updateprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addComponent(dtp_updateexpire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pb_updateimg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_updateupload, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_updateerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_refreshupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        jTabbedPane5.addTab("UPDATE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(46, 51, 73));

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 126, 249));
        jLabel9.setText("Product ID");

        tbl_showdelete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Brand", "Quantity", "Manufacture", "Expire", "Price", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_showdelete.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_showdelete);

        btn_refreshdelete.setBackground(new java.awt.Color(46, 51, 73));
        btn_refreshdelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_refreshdelete.setForeground(new java.awt.Color(0, 126, 249));
        btn_refreshdelete.setText("Refresh");
        btn_refreshdelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_refreshdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshdeleteActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(46, 51, 73));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(0, 126, 249));
        btn_delete.setText("DELETE");
        btn_delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 126, 249), 2));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_deleteerror.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_deleteerror.setForeground(new java.awt.Color(204, 0, 0));
        txt_deleteerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_deleteerror.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txt_deleteid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_deleteerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_refreshdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(txt_deleteerror, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_deleteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_refreshdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jTabbedPane5.addTab("DELETE", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane5)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        BufferedImage img = null;
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        try{
            
            img = ImageIO.read(new File(filename));  
            
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

        Image image = img.getScaledInstance(pb_img.getWidth(), pb_img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageicon = new ImageIcon(image);
        pb_img.setIcon(imageicon);
    }//GEN-LAST:event_btn_uploadActionPerformed
    String filename;
    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
       refresh();
       
    }//GEN-LAST:event_btn_refreshActionPerformed
    public void refresh()
    {
        
        tbl_products.getTableHeader().setReorderingAllowed(false);
        ResultSet rs = CProduct.getProducts();

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Name");
        dtm.addColumn("Brand");
        dtm.addColumn("Quantity");
        dtm.addColumn("Manu Date");
        dtm.addColumn("Exp Date");
        dtm.addColumn("Price");
        dtm.addColumn("Image");
        try{
            while(rs.next()){
                String[] values = new String[8];
                values[0] = rs.getString(1);
                values[1] = rs.getString(2);
                values[2] = rs.getString(3);
                values[3] = rs.getString(4);
                values[4] = rs.getString(5);
                values[5] = rs.getString(6);
                values[6] = rs.getString(7);
                values[7] = rs.getString(8);
                dtm.addRow(values);
            }
            tbl_products.setModel(dtm);

        }
        catch(SQLException e)
        {
            e.printStackTrace();
        }
    }
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if(txt_name.getText().isEmpty())
        {
            txt_adderror.setText("*Name cannot be blank");
        }
        else if(txt_brand.getText().isEmpty())
        {
            txt_adderror.setText("*Brand cannot be blank");
        }
        else if (txt_quantity.getText().isEmpty())
        {
            txt_adderror.setText("*Quantity cannot be blank");
        }
        else if(!txt_quantity.getText().matches("\\d+"))
        {
            txt_adderror.setText("*Quantity can only contain numbers");
        }
        else if(txt_price.getText().isEmpty())
        {
            txt_adderror.setText("*Price cannot be blank");
        }
        else if (!txt_price.getText().matches("\\d+"))
        {
            txt_adderror.setText("*Price cannot contain letters");
        }        
        else{
            String image =filename.replace("\\", "\\\\");
            int i = CProduct.addProduct(txt_name.getText(),txt_brand.getText(),Integer.parseInt(txt_quantity.getText()),dtp_manufacture.getDate(), dtp_expire.getDate(),Integer.parseInt(txt_price.getText()), image);

            if (i == 1)
            {
             JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(),"Product Added Successfully","Info",JOptionPane.INFORMATION_MESSAGE);
             btn_refreshActionPerformed(evt);
            }
            else
            {
             JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(),"Could Not Add Product","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            CProduct.insertDataChange(CProduct.getProductIdBYName(txt_name.getText()), VLogin.emp_id);
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_refreshdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshdeleteActionPerformed
       refreshDeleteTable();
    }//GEN-LAST:event_btn_refreshdeleteActionPerformed
    public void refreshDeleteTable()
    {
         tbl_products.setEnabled(false);
        tbl_products.getTableHeader().setReorderingAllowed(false);
        ResultSet rs = CProduct.getProducts();

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Name");
        dtm.addColumn("Brand");
        dtm.addColumn("Quantity");
        dtm.addColumn("Manu Date");
        dtm.addColumn("Exp Date");
        dtm.addColumn("Price");
        dtm.addColumn("Image");
        try{
            while(rs.next()){
                String[] values = new String[8];
                values[0] = rs.getString(1);
                values[1] = rs.getString(2);
                values[2] = rs.getString(3);
                values[3] = rs.getString(4);
                values[4] = rs.getString(5);
                values[5] = rs.getString(6);
                values[6] = rs.getString(7);
                values[7] = rs.getString(8);
                dtm.addRow(values);
            }
            
            tbl_showdelete.setModel(dtm);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    private void btn_updateuploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateuploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        BufferedImage img = null;
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        try{
            img = ImageIO.read(new File(filename));
        }
        catch(IOException e)
        {
            e.printStackTrace();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

        Image image = img.getScaledInstance(pb_img.getWidth(), pb_img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageicon = new ImageIcon(image);
        pb_updateimg.setIcon(imageicon);
    }//GEN-LAST:event_btn_updateuploadActionPerformed

    private void btn_refreshupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshupdateActionPerformed
       refreshUpdateTable();
    }//GEN-LAST:event_btn_refreshupdateActionPerformed
    
    public void refreshUpdateTable()
    {
         
        tbl_products.getTableHeader().setReorderingAllowed(false);
        ResultSet rs = CProduct.getProducts();

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID");
        dtm.addColumn("Name");
        dtm.addColumn("Brand");
        dtm.addColumn("Quantity");
        dtm.addColumn("Manu Date");
        dtm.addColumn("Exp Date");
        dtm.addColumn("Price");
        dtm.addColumn("Image");
        try{
            while(rs.next()){
                String[] values = new String[8];
                values[0] = rs.getString(1);
                values[1] = rs.getString(2);
                values[2] = rs.getString(3);
                values[3] = rs.getString(4);
                values[4] = rs.getString(5);
                values[5] = rs.getString(6);
                values[6] = rs.getString(7);
                values[7] = rs.getString(8);
                dtm.addRow(values);
            }
            tbl_showupdate.setModel(dtm);

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        txt_updateid.setEditable(true);
    }
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        
        if(txt_updatename.getText().isEmpty())
        {
            txt_updateerror.setText("*Name cannot be blank");
        }
        else if(txt_updatebrand.getText().isEmpty())
        {
            txt_updateerror.setText("*Brand cannot be blank");
        }
        else if (txt_updatequantity.getText().isEmpty())
        {
            txt_updateerror.setText("*Quantity cannot be blank");
        }
        else if(!txt_updatequantity.getText().matches("\\d+"))
        {
            txt_updateerror.setText("*Quantity can only contain numbers");
        }
        else if(txt_updateprice.getText().isEmpty())
        {
            txt_updateerror.setText("*Price cannot be blank");
        }
        else if (!txt_updateprice.getText().matches("\\d+"))
        {
            txt_updateerror.setText("*Price cannot contain letters");
        }       
        else if (txt_updateid.getText().isEmpty())
        {
            txt_updateerror.setText("*Product id cannot be blank");
        }
        else if(!txt_updateid.getText().matches("\\d+"))
        {
            txt_updateerror.setText("*Product id cannot contain letters");
        }
        else{
            String image =filename.replace("\\", "\\\\");
            int i = CProduct.updateProduct(Integer.parseInt(txt_updateid.getText()),txt_updatename.getText(),txt_updatebrand.getText(),Integer.parseInt(txt_updatequantity.getText()),dtp_updatemanufacture.getDate(), dtp_updateexpire.getDate(),Integer.parseInt(txt_updateprice.getText()), image);

            if (i == 1)
            {
             JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(),"Product Updated Successfully","Info",JOptionPane.INFORMATION_MESSAGE);
             CProduct.insertDataChange(Integer.parseInt(txt_updateprice.getText()), VLogin.emp_id);
             btn_refreshupdateActionPerformed(evt);
            }
            else
            {
             JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(),"Could Not Update Product","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_loadproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadproductActionPerformed
        // TODO add your handling code here:
        if(txt_updateid.getText().isEmpty())
        {
            txt_updateerror.setText("Product id cannot be blank");
        }
        else if(!txt_updateid.getText().matches("\\d+"))
        {
            txt_updateerror.setText("Product id cannot contain letters");
        }
        else
        {
            
            ResultSet rs = CProduct.loadProductById(Integer.parseInt(txt_updateid.getText()));
            try{    
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "No product with this product id","Error",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    
                    do{
                            
                        txt_updatename.setText(rs.getString(1));
                        txt_updatebrand.setText(rs.getString(2));
                        txt_updatequantity.setText(rs.getString(3));
                        dtp_updatemanufacture.setDate(rs.getDate(4));
                        dtp_updateexpire.setDate(rs.getDate(5));
                        String price = Integer.toString(rs.getInt(6));
                        txt_updateprice.setText(price);
                        filename = rs.getString(7);
                        BufferedImage img = ImageIO.read(new File(rs.getString(7)));
                        Image image = img.getScaledInstance(pb_img.getWidth(), pb_img.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon imageicon = new ImageIcon(image);
                        pb_updateimg.setIcon(imageicon);
                    }
                    while(rs.next());
                    
                }
                }   
                catch(Exception e)
                    {
                        e.printStackTrace();
                    }
            txt_updateid.setEditable(false);
        }
            
        
        
    }//GEN-LAST:event_btn_loadproductActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        if(txt_deleteid.getText().isEmpty())
        {
            txt_deleteerror.setText("Product id cannot be blank");
        }
        else if(!txt_deleteid.getText().matches("\\d+"))
        {
            txt_deleteerror.setText("Product id cannot contain letters");
        }
        else{
            
            int i = CProduct.deleteProduct(Integer.parseInt(txt_deleteid.getText()));
            
            if(i==1)
            {
                JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "Product Deleted Successfully","Info",JOptionPane.INFORMATION_MESSAGE);
                CProduct.insertDataChange(Integer.parseInt(txt_deleteid.getText()), VLogin.emp_id);
                btn_refreshdeleteActionPerformed(evt);
            }
            else
            {
                JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), "Product id mentioned id does not exist","Error",JOptionPane.ERROR_MESSAGE);
            }
            
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbl_productsMouseClicked
    String image_tbl = "";
    private void tbl_showupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_showupdateMouseClicked
        // TODO add your handling code here:
          int selectedRow = tbl_showupdate.getSelectedRow();
        DefaultTableModel dtm = (DefaultTableModel)tbl_showupdate.getModel();
        txt_updateid.setText(dtm.getValueAt(selectedRow, 0).toString());
        txt_updatename.setText(dtm.getValueAt(selectedRow, 1).toString());
        txt_updatebrand.setText(dtm.getValueAt(selectedRow, 2).toString());
        txt_updatequantity.setText(dtm.getValueAt(selectedRow, 3).toString());
        txt_updateprice.setText(dtm.getValueAt(selectedRow, 6).toString());
        image_tbl = dtm.getValueAt(selectedRow, 7).toString();
       filename = dtm.getValueAt(selectedRow, 7).toString();
        try{
                        BufferedImage img = ImageIO.read(new File(image_tbl));
                        Image image = img.getScaledInstance(pb_updateimg.getWidth(), pb_updateimg.getHeight(), Image.SCALE_SMOOTH);
                        ImageIcon imageicon = new ImageIcon(image);
                         pb_updateimg.setIcon(imageicon);
            String mnf_dt =dtm.getValueAt(selectedRow, 4).toString() ;
            String exp_dt =dtm.getValueAt(selectedRow, 5).toString() ;
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(mnf_dt);
            java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(exp_dt);
            dtp_updatemanufacture.setDate(date);
            dtp_updateexpire.setDate(date2);
        
        }
        catch(ParseException e)
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), e.getMessage());
        }
        catch(IOException e)
        {
            JOptionPane.showMessageDialog(CMessageManagement.getVisibleContent(), e.getMessage());
        }
    }//GEN-LAST:event_tbl_showupdateMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_loadproduct;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_refreshdelete;
    private javax.swing.JButton btn_refreshupdate;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_updateupload;
    private javax.swing.JButton btn_upload;
    private com.toedter.calendar.JDateChooser dtp_expire;
    private com.toedter.calendar.JDateChooser dtp_manufacture;
    private com.toedter.calendar.JDateChooser dtp_updateexpire;
    private com.toedter.calendar.JDateChooser dtp_updatemanufacture;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel pb_img;
    private javax.swing.JLabel pb_updateimg;
    private javax.swing.JTable tbl_products;
    private javax.swing.JTable tbl_showdelete;
    private javax.swing.JTable tbl_showupdate;
    private javax.swing.JLabel txt_adderror;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JLabel txt_deleteerror;
    private javax.swing.JTextField txt_deleteid;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_updatebrand;
    private javax.swing.JLabel txt_updateerror;
    private javax.swing.JTextField txt_updateid;
    private javax.swing.JTextField txt_updatename;
    private javax.swing.JTextField txt_updateprice;
    private javax.swing.JTextField txt_updatequantity;
    // End of variables declaration//GEN-END:variables
}
